# Generated by Django 3.0.4 on 2020-05-15 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='applications/static'),
            preserve_default=False,
        ),
    ]
