# Generated by Django 3.0.4 on 2020-05-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationsubfield',
            name='expDate',
            field=models.DateField(null=True, verbose_name='Ημερομηνία λήξης'),
        ),
    ]
