# Generated by Django 3.0.4 on 2020-05-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_applicationform_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='status',
            field=models.CharField(default='Pending', max_length=100, verbose_name='Κατασταση'),
        ),
        migrations.CreateModel(
            name='ApplicationSubField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=100, verbose_name='Κατάσταση')),
                ('expDate', models.DateField(verbose_name='Ημερομηνία λήξης')),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='applications.ApplicationForm')),
                ('subField', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounts.SubField')),
            ],
            options={
                'verbose_name': 'Πεδίο',
                'verbose_name_plural': 'Πεδία',
                'ordering': ['subField'],
            },
        ),
        migrations.AddField(
            model_name='applicationform',
            name='subfields',
            field=models.ManyToManyField(through='applications.ApplicationSubField', to='accounts.SubField', verbose_name='Πεδια'),
        ),
    ]
