# Generated by Django 3.0.7 on 2020-06-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20200516_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='file',
            field=models.FileField(upload_to='applications/static/esyd_files'),
        ),
    ]
