# Generated by Django 3.0.4 on 2020-05-28 18:37

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20200528_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='file',
            field=models.FileField(upload_to=applications.models.generate_filename, verbose_name='Αρχείο απόδειξης τεχνικής επάρκειας προσωπικού'),
        ),
    ]
