# Generated by Django 3.0.4 on 2020-06-11 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200528_1837'),
        ('applications', '0007_applicationypanform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationypanform',
            name='esyd_app',
        ),
        migrations.CreateModel(
            name='ApplicationYpanSubField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Σε εκκρεμότητα', 'Σε εκκρεμότητα'), ('Απορρίφθηκε', 'Απορρίφθηκε'), ('Εγκρίθηκε', 'Εγκρίθηκε')], default='Σε εκκρεμότητα', max_length=30, verbose_name='Κατάσταση')),
                ('expDate', models.DateField(null=True, verbose_name='Ημερομηνία λήξης')),
                ('application', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ypan_subfields', to='applications.ApplicationYpanForm')),
                ('subField', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ypan_apps', to='accounts.SubField')),
            ],
            options={
                'verbose_name': 'Πεδίο',
                'verbose_name_plural': 'Πεδία',
                'ordering': ['subField'],
            },
        ),
        migrations.AddField(
            model_name='applicationypanform',
            name='subfields',
            field=models.ManyToManyField(through='applications.ApplicationYpanSubField', to='accounts.SubField', verbose_name='Πεδια'),
        ),
    ]
