# Generated by Django 3.0.4 on 2020-06-11 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20200611_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationypanform',
            name='Activity_Field_App',
        ),
        migrations.RemoveField(
            model_name='applicationypanform',
            name='Cert_ID',
        ),
    ]
