# Generated by Django 3.0.4 on 2020-06-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_auto_20200611_2330'),
        ('applications', '0005_auto_20200612_2325'),
    ]

    operations = [
    ]
