# Generated by Django 3.0.7 on 2020-06-13 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20200613_2338'),
        ('applications', '0009_auto_20200611_2330'),
    ]

    operations = [
    ]
