# Generated by Django 3.0.4 on 2020-06-13 13:39

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_merge_20200613_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='file',
            field=models.FileField(upload_to=applications.models.generate_filename, verbose_name='Αρχείο απόδειξης τεχνικής επάρκειας προσωπικού'),
        ),
    ]
