# Generated by Django 3.0.4 on 2020-06-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_applicationypanform_civil_expdate'),
        ('applications', '0005_auto_20200612_2325'),
    ]

    operations = [
    ]
