# Generated by Django 3.0.7 on 2020-06-18 13:19

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_merge_20200614_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='file',
            field=models.FileField(upload_to=applications.models.generate_filename, verbose_name='Αρχείο απόδειξης τεχνικής επάρκειας προσωπικού'),
        ),
        migrations.AlterField(
            model_name='applicationypanform',
            name='Civil_ExpDate',
            field=models.DateField(verbose_name='Ημ/νία λήξης ασφάλισης'),
        ),
    ]
