# Generated by Django 3.0.4 on 2020-05-10 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=250, verbose_name='Ονομασία')),
                ('distTitle', models.CharField(blank=True, max_length=100, verbose_name='Διακριτικός Τίτλος')),
                ('afm', models.CharField(blank=True, max_length=20, verbose_name='ΑΦΜ')),
                ('doy', models.CharField(blank=True, max_length=100, verbose_name='Δ.Ο.Υ.')),
                ('gemi', models.CharField(blank=True, max_length=20, verbose_name='ΓΕΜΗ')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Διεύθυνση')),
                ('postalCode', models.CharField(blank=True, max_length=10, verbose_name='Ταχ. Κώδικας')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Τηλέφωνο')),
                ('fax', models.CharField(blank=True, max_length=15, verbose_name='Φαξ')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('contactPerson', models.CharField(blank=True, max_length=100, verbose_name='Πρόσωπο Επικοινωνίας')),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Όνομα Χρήστη')),
            ],
        ),
    ]
