# Generated by Django 3.0.4 on 2020-05-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=25, verbose_name='Όνομα Χρήστη')),
                ('companyName', models.CharField(max_length=250, verbose_name='Ονομασία')),
                ('distTitle', models.CharField(max_length=100, verbose_name='Διακριτικός Τίτλος')),
                ('afm', models.CharField(max_length=20, verbose_name='ΑΦΜ')),
                ('doy', models.CharField(max_length=100, verbose_name='Δ.Ο.Υ.')),
                ('gemi', models.CharField(max_length=20, verbose_name='ΓΕΜΗ')),
                ('address', models.CharField(max_length=250, verbose_name='Διεύθυνση')),
                ('postalCode', models.CharField(max_length=10, verbose_name='Ταχ. Κώδικας')),
                ('phone', models.CharField(max_length=15, verbose_name='Τηλέφωνο')),
                ('fax', models.CharField(max_length=15, verbose_name='Φαξ')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('contactPerson', models.CharField(max_length=100, verbose_name='Πρόσωπο Επικοινωνίας')),
            ],
        ),
    ]
