# Generated by Django 3.0.4 on 2020-05-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subfield',
            name='subField',
            field=models.CharField(max_length=250, verbose_name='Υπομέρους Θεματικό Πεδίο'),
        ),
        migrations.AlterUniqueTogether(
            name='subfield',
            unique_together={('regulation', 'subField')},
        ),
    ]
