# Generated by Django 3.0.4 on 2020-05-14 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeiristisEsyd',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(blank=True, max_length=250, verbose_name='Όνομα')),
                ('lastname', models.CharField(blank=True, max_length=100, verbose_name='Επίθετο')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Τμήμα')),
                ('desk', models.CharField(max_length=100, verbose_name='Γραφείο')),
            ],
        ),
        migrations.CreateModel(
            name='XeiristisYpourgeiou',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(blank=True, max_length=250, verbose_name='Όνομα')),
                ('lastname', models.CharField(blank=True, max_length=100, verbose_name='Επίθετο')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Τμήμα')),
                ('desk', models.CharField(max_length=100, verbose_name='Γραφείο')),
            ],
        ),
    ]
