# Generated by Django 3.0.4 on 2020-05-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='userName',
            field=models.CharField(max_length=25, primary_key=True, serialize=False, verbose_name='Όνομα Χρήστη'),
        ),
    ]
