# Generated by Django 3.0.4 on 2020-05-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_xeiristisesyd_xeiristisypourgeiou'),
    ]

    operations = [
        migrations.AddField(
            model_name='xeiristisesyd',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='xeiristisypourgeiou',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
