# Generated by Django 3.0.4 on 2020-05-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200517_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subfield',
            options={'ordering': ['regulation', 'subField'], 'verbose_name': 'Πεδίο', 'verbose_name_plural': 'Πεδία'},
        ),
    ]
