# Generated by Django 3.0.4 on 2020-05-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200511_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantprofile',
            old_name='userName',
            new_name='user',
        ),
    ]
