# Generated by Django 3.0.4 on 2020-05-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200511_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=250, unique=True, verbose_name='Nομοθετικη Διάταξη')),
            ],
        ),
        migrations.CreateModel(
            name='SubField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subField', models.CharField(max_length=250, unique=True, verbose_name='Υπομέρους Θεματικό Πεδίο')),
                ('regulation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Regulation')),
            ],
        ),
    ]
